name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # Change this to your main branch
      
jobs:
  deploy:
    runs-on: self-hosted
    # runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
