name: Test Server Connection

on:
  push:
    branches:
      - main

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Send Request to Server
        run: |
          curl http://223.31.190.212/api/data
